const listaJugadores = [
  {
    jugador: "Kareem Abdul-Jabbar",
    rival: "Golden State Warriors",
    fase: "Liga regular",
    puntos: 8,
    rebotes: 34,
    valoracion: 41,
  },
  {
    jugador: "Kareem Abdul-Jabbar",
    rival: "Houston Rockets",
    fase: "Liga regular",
    puntos: 64,
    rebotes: 28,
    valoracion: 23,
  },
  {
    jugador: "Michael Jordan",
    rival: "San Antonio Spurs",
    fase: "Finales",
    puntos: 82,
    rebotes: 31,
    valoracion: 12,
  },
  {
    jugador: "LeBron James",
    rival: "Dallas Mavericks",
    fase: "Playoff",
    puntos: 21,
    rebotes: 25,
    valoracion: 35,
  },
  {
    jugador: "LeBron James",
    rival: "Golden State Warriors",
    fase: "Finales",
    puntos: 36,
    rebotes: 26,
    valoracion: 15,
  },
  {
    jugador: "Kareem Abdul-Jabbar",
    rival: "Boston Celtics",
    fase: "Playoff",
    puntos: 75,
    rebotes: 39,
    valoracion: 21,
  },
  {
    jugador: "Kobe Bryant",
    rival: "Philadelphia 76ers",
    fase: "Finales",
    puntos: 64,
    rebotes: 23,
    valoracion: 12,
  },
  {
    jugador: "Kareem Abdul-Jabbar",
    rival: "Philadelphia 76ers",
    fase: "Finales",
    puntos: 93,
    rebotes: 33,
    valoracion: 20,
  },
  {
    jugador: "Kobe Bryant",
    rival: "San Antonio Spurs",
    fase: "Liga regular",
    puntos: 40,
    rebotes: 17,
    valoracion: 16,
  },
  {
    jugador: "LeBron James",
    rival: "San Antonio Spurs",
    fase: "Liga regular",
    puntos: 6,
    rebotes: 6,
    valoracion: 2,
  },
  {
    jugador: "Kareem Abdul-Jabbar",
    rival: "Dallas Mavericks",
    fase: "Playoff",
    puntos: 27,
    rebotes: 40,
    valoracion: 23,
  },
  {
    jugador: "Wilt Chamberlain",
    rival: "Miami Heat",
    fase: "Finales",
    puntos: 64,
    rebotes: 25,
    valoracion: 30,
  },
  {
    jugador: "Shaquille O'Neal",
    rival: "Dallas Mavericks",
    fase: "Finales",
    puntos: 86,
    rebotes: 38,
    valoracion: 23,
  },
  {
    jugador: "Tim Duncan",
    rival: "Chicago Bulls",
    fase: "Liga regular",
    puntos: 67,
    rebotes: 4,
    valoracion: 48,
  },
  {
    jugador: "Magic Johnson",
    rival: "Toronto Raptors",
    fase: "Liga regular",
    puntos: 85,
    rebotes: 7,
    valoracion: 15,
  },
  {
    jugador: "Larry Bird",
    rival: "Chicago Bulls",
    fase: "Liga regular",
    puntos: 45,
    rebotes: 38,
    valoracion: 14,
  },
  {
    jugador: "Kobe Bryant",
    rival: "Dallas Mavericks",
    fase: "Playoff",
    puntos: 55,
    rebotes: 14,
    valoracion: 47,
  },
  {
    jugador: "Larry Bird",
    rival: "Miami Heat",
    fase: "Liga regular",
    puntos: 75,
    rebotes: 25,
    valoracion: 40,
  },
  {
    jugador: "Kobe Bryant",
    rival: "Toronto Raptors",
    fase: "Finales",
    puntos: 97,
    rebotes: 6,
    valoracion: 29,
  },
  {
    jugador: "Magic Johnson",
    rival: "Toronto Raptors",
    fase: "Liga regular",
    puntos: 57,
    rebotes: 15,
    valoracion: 42,
  },
  {
    jugador: "LeBron James",
    rival: "Golden State Warriors",
    fase: "Playoff",
    puntos: 1,
    rebotes: 13,
    valoracion: 37,
  },
  {
    jugador: "LeBron James",
    rival: "Boston Celtics",
    fase: "Playoff",
    puntos: 74,
    rebotes: 39,
    valoracion: 3,
  },
  {
    jugador: "Bill Russell",
    rival: "Houston Rockets",
    fase: "Playoff",
    puntos: 64,
    rebotes: 4,
    valoracion: 30,
  },
  {
    jugador: "Wilt Chamberlain",
    rival: "Philadelphia 76ers",
    fase: "Liga regular",
    puntos: 72,
    rebotes: 19,
    valoracion: 5,
  },
  {
    jugador: "Shaquille O'Neal",
    rival: "Los Angeles Lakers",
    fase: "Playoff",
    puntos: 64,
    rebotes: 34,
    valoracion: 10,
  },
  {
    jugador: "Michael Jordan",
    rival: "Golden State Warriors",
    fase: "Liga regular",
    puntos: 28,
    rebotes: 23,
    valoracion: 20,
  },
  {
    jugador: "Kareem Abdul-Jabbar",
    rival: "Dallas Mavericks",
    fase: "Playoff",
    puntos: 61,
    rebotes: 29,
    valoracion: 5,
  },
  {
    jugador: "Michael Jordan",
    rival: "Los Angeles Lakers",
    fase: "Finales",
    puntos: 51,
    rebotes: 13,
    valoracion: 34,
  },
  {
    jugador: "Tim Duncan",
    rival: "Philadelphia 76ers",
    fase: "Finales",
    puntos: 64,
    rebotes: 30,
    valoracion: 34,
  },
  {
    jugador: "LeBron James",
    rival: "San Antonio Spurs",
    fase: "Playoff",
    puntos: 11,
    rebotes: 4,
    valoracion: 48,
  },
  {
    jugador: "Larry Bird",
    rival: "Boston Celtics",
    fase: "Finales",
    puntos: 94,
    rebotes: 10,
    valoracion: 17,
  },
  {
    jugador: "Magic Johnson",
    rival: "Philadelphia 76ers",
    fase: "Liga regular",
    puntos: 59,
    rebotes: 12,
    valoracion: 31,
  },
  {
    jugador: "LeBron James",
    rival: "San Antonio Spurs",
    fase: "Playoff",
    puntos: 95,
    rebotes: 7,
    valoracion: 36,
  },
  {
    jugador: "Bill Russell",
    rival: "Chicago Bulls",
    fase: "Liga regular",
    puntos: 65,
    rebotes: 38,
    valoracion: 35,
  },
  {
    jugador: "Shaquille O'Neal",
    rival: "Miami Heat",
    fase: "Playoff",
    puntos: 34,
    rebotes: 40,
    valoracion: 21,
  },
  {
    jugador: "Tim Duncan",
    rival: "Boston Celtics",
    fase: "Liga regular",
    puntos: 84,
    rebotes: 10,
    valoracion: 26,
  },
  {
    jugador: "Magic Johnson",
    rival: "Boston Celtics",
    fase: "Playoff",
    puntos: 51,
    rebotes: 9,
    valoracion: 31,
  },
  {
    jugador: "Magic Johnson",
    rival: "Toronto Raptors",
    fase: "Liga regular",
    puntos: 5,
    rebotes: 17,
    valoracion: 43,
  },
  {
    jugador: "Magic Johnson",
    rival: "San Antonio Spurs",
    fase: "Finales",
    puntos: 94,
    rebotes: 17,
    valoracion: 39,
  },
  {
    jugador: "Wilt Chamberlain",
    rival: "Philadelphia 76ers",
    fase: "Finales",
    puntos: 12,
    rebotes: 21,
    valoracion: 16,
  },
  {
    jugador: "Wilt Chamberlain",
    rival: "Golden State Warriors",
    fase: "Finales",
    puntos: 6,
    rebotes: 2,
    valoracion: 50,
  },
  {
    jugador: "LeBron James",
    rival: "Toronto Raptors",
    fase: "Liga regular",
    puntos: 77,
    rebotes: 29,
    valoracion: 26,
  },
  {
    jugador: "LeBron James",
    rival: "San Antonio Spurs",
    fase: "Finales",
    puntos: 82,
    rebotes: 7,
    valoracion: 15,
  },
  {
    jugador: "Tim Duncan",
    rival: "San Antonio Spurs",
    fase: "Playoff",
    puntos: 68,
    rebotes: 2,
    valoracion: 42,
  },
  {
    jugador: "Larry Bird",
    rival: "Philadelphia 76ers",
    fase: "Liga regular",
    puntos: 59,
    rebotes: 19,
    valoracion: 13,
  },
  {
    jugador: "Tim Duncan",
    rival: "Toronto Raptors",
    fase: "Finales",
    puntos: 2,
    rebotes: 21,
    valoracion: 30,
  },
  {
    jugador: "Bill Russell",
    rival: "Golden State Warriors",
    fase: "Liga regular",
    puntos: 88,
    rebotes: 25,
    valoracion: 19,
  },
  {
    jugador: "Bill Russell",
    rival: "Dallas Mavericks",
    fase: "Liga regular",
    puntos: 12,
    rebotes: 5,
    valoracion: 13,
  },
  {
    jugador: "LeBron James",
    rival: "Philadelphia 76ers",
    fase: "Finales",
    puntos: 98,
    rebotes: 15,
    valoracion: 4,
  },
  {
    jugador: "Michael Jordan",
    rival: "Philadelphia 76ers",
    fase: "Liga regular",
    puntos: 88,
    rebotes: 24,
    valoracion: 7,
  },
  {
    jugador: "Kobe Bryant",
    rival: "Los Angeles Lakers",
    fase: "Finales",
    puntos: 82,
    rebotes: 7,
    valoracion: 40,
  },
  {
    jugador: "LeBron James",
    rival: "Houston Rockets",
    fase: "Liga regular",
    puntos: 17,
    rebotes: 23,
    valoracion: 4,
  },
  {
    jugador: "Kobe Bryant",
    rival: "Dallas Mavericks",
    fase: "Playoff",
    puntos: 20,
    rebotes: 2,
    valoracion: 39,
  },
  {
    jugador: "Bill Russell",
    rival: "Dallas Mavericks",
    fase: "Finales",
    puntos: 10,
    rebotes: 34,
    valoracion: 26,
  },
  {
    jugador: "Kareem Abdul-Jabbar",
    rival: "Dallas Mavericks",
    fase: "Playoff",
    puntos: 46,
    rebotes: 18,
    valoracion: 19,
  },
  {
    jugador: "Wilt Chamberlain",
    rival: "Miami Heat",
    fase: "Finales",
    puntos: 31,
    rebotes: 29,
    valoracion: 16,
  },
  {
    jugador: "LeBron James",
    rival: "San Antonio Spurs",
    fase: "Liga regular",
    puntos: 95,
    rebotes: 2,
    valoracion: 19,
  },
  {
    jugador: "Kobe Bryant",
    rival: "Philadelphia 76ers",
    fase: "Liga regular",
    puntos: 96,
    rebotes: 16,
    valoracion: 16,
  },
  {
    jugador: "Michael Jordan",
    rival: "Houston Rockets",
    fase: "Finales",
    puntos: 52,
    rebotes: 13,
    valoracion: 50,
  },
  {
    jugador: "Kobe Bryant",
    rival: "Golden State Warriors",
    fase: "Liga regular",
    puntos: 95,
    rebotes: 26,
    valoracion: 33,
  },
  {
    jugador: "Shaquille O'Neal",
    rival: "Houston Rockets",
    fase: "Finales",
    puntos: 21,
    rebotes: 29,
    valoracion: 38,
  },
  {
    jugador: "Kobe Bryant",
    rival: "San Antonio Spurs",
    fase: "Finales",
    puntos: 15,
    rebotes: 19,
    valoracion: 37,
  },
  {
    jugador: "Shaquille O'Neal",
    rival: "San Antonio Spurs",
    fase: "Finales",
    puntos: 4,
    rebotes: 8,
    valoracion: 8,
  },
  {
    jugador: "Kareem Abdul-Jabbar",
    rival: "San Antonio Spurs",
    fase: "Playoff",
    puntos: 42,
    rebotes: 33,
    valoracion: 14,
  },
  {
    jugador: "LeBron James",
    rival: "Los Angeles Lakers",
    fase: "Liga regular",
    puntos: 13,
    rebotes: 24,
    valoracion: 31,
  },
  {
    jugador: "Tim Duncan",
    rival: "Boston Celtics",
    fase: "Finales",
    puntos: 4,
    rebotes: 36,
    valoracion: 41,
  },
  {
    jugador: "Magic Johnson",
    rival: "Philadelphia 76ers",
    fase: "Playoff",
    puntos: 6,
    rebotes: 32,
    valoracion: 26,
  },
  {
    jugador: "Larry Bird",
    rival: "Chicago Bulls",
    fase: "Playoff",
    puntos: 38,
    rebotes: 31,
    valoracion: 22,
  },
  {
    jugador: "Larry Bird",
    rival: "Toronto Raptors",
    fase: "Playoff",
    puntos: 56,
    rebotes: 8,
    valoracion: 30,
  },
  {
    jugador: "Larry Bird",
    rival: "Miami Heat",
    fase: "Liga regular",
    puntos: 91,
    rebotes: 32,
    valoracion: 8,
  },
  {
    jugador: "Tim Duncan",
    rival: "Boston Celtics",
    fase: "Playoff",
    puntos: 7,
    rebotes: 35,
    valoracion: 20,
  },
  {
    jugador: "LeBron James",
    rival: "San Antonio Spurs",
    fase: "Playoff",
    puntos: 41,
    rebotes: 12,
    valoracion: 36,
  },
  {
    jugador: "Magic Johnson",
    rival: "San Antonio Spurs",
    fase: "Liga regular",
    puntos: 54,
    rebotes: 18,
    valoracion: 14,
  },
  {
    jugador: "Bill Russell",
    rival: "Los Angeles Lakers",
    fase: "Finales",
    puntos: 54,
    rebotes: 29,
    valoracion: 6,
  },
  {
    jugador: "Kobe Bryant",
    rival: "Toronto Raptors",
    fase: "Liga regular",
    puntos: 61,
    rebotes: 11,
    valoracion: 14,
  },
  {
    jugador: "Kobe Bryant",
    rival: "Toronto Raptors",
    fase: "Playoff",
    puntos: 11,
    rebotes: 40,
    valoracion: 49,
  },
  {
    jugador: "Larry Bird",
    rival: "Miami Heat",
    fase: "Finales",
    puntos: 63,
    rebotes: 26,
    valoracion: 31,
  },
  {
    jugador: "Michael Jordan",
    rival: "Los Angeles Lakers",
    fase: "Playoff",
    puntos: 30,
    rebotes: 38,
    valoracion: 5,
  },
  {
    jugador: "Larry Bird",
    rival: "Dallas Mavericks",
    fase: "Finales",
    puntos: 79,
    rebotes: 12,
    valoracion: 15,
  },
  {
    jugador: "LeBron James",
    rival: "Boston Celtics",
    fase: "Finales",
    puntos: 88,
    rebotes: 6,
    valoracion: 32,
  },
  {
    jugador: "Larry Bird",
    rival: "Miami Heat",
    fase: "Liga regular",
    puntos: 3,
    rebotes: 33,
    valoracion: 41,
  },
  {
    jugador: "Tim Duncan",
    rival: "Dallas Mavericks",
    fase: "Liga regular",
    puntos: 71,
    rebotes: 34,
    valoracion: 23,
  },
  {
    jugador: "Shaquille O'Neal",
    rival: "Philadelphia 76ers",
    fase: "Liga regular",
    puntos: 69,
    rebotes: 31,
    valoracion: 15,
  },
  {
    jugador: "Kobe Bryant",
    rival: "Chicago Bulls",
    fase: "Playoff",
    puntos: 56,
    rebotes: 8,
    valoracion: 38,
  },
  {
    jugador: "Magic Johnson",
    rival: "Toronto Raptors",
    fase: "Finales",
    puntos: 52,
    rebotes: 35,
    valoracion: 50,
  },
  {
    jugador: "Larry Bird",
    rival: "Chicago Bulls",
    fase: "Liga regular",
    puntos: 88,
    rebotes: 5,
    valoracion: 36,
  },
  {
    jugador: "Shaquille O'Neal",
    rival: "Toronto Raptors",
    fase: "Playoff",
    puntos: 33,
    rebotes: 8,
    valoracion: 24,
  },
  {
    jugador: "Magic Johnson",
    rival: "Miami Heat",
    fase: "Playoff",
    puntos: 71,
    rebotes: 10,
    valoracion: 31,
  },
  {
    jugador: "Bill Russell",
    rival: "Los Angeles Lakers",
    fase: "Playoff",
    puntos: 9,
    rebotes: 39,
    valoracion: 50,
  },
  {
    jugador: "Wilt Chamberlain",
    rival: "Toronto Raptors",
    fase: "Finales",
    puntos: 57,
    rebotes: 33,
    valoracion: 29,
  },
  {
    jugador: "Michael Jordan",
    rival: "Chicago Bulls",
    fase: "Finales",
    puntos: 45,
    rebotes: 1,
    valoracion: 24,
  },
  {
    jugador: "Bill Russell",
    rival: "Houston Rockets",
    fase: "Liga regular",
    puntos: 83,
    rebotes: 19,
    valoracion: 40,
  },
  {
    jugador: "LeBron James",
    rival: "Chicago Bulls",
    fase: "Finales",
    puntos: 18,
    rebotes: 12,
    valoracion: 45,
  },
  {
    jugador: "Magic Johnson",
    rival: "Dallas Mavericks",
    fase: "Liga regular",
    puntos: 22,
    rebotes: 3,
    valoracion: 24,
  },
  {
    jugador: "Wilt Chamberlain",
    rival: "Boston Celtics",
    fase: "Finales",
    puntos: 85,
    rebotes: 11,
    valoracion: 10,
  },
  {
    jugador: "Michael Jordan",
    rival: "Boston Celtics",
    fase: "Liga regular",
    puntos: 18,
    rebotes: 22,
    valoracion: 6,
  },
  {
    jugador: "Tim Duncan",
    rival: "Toronto Raptors",
    fase: "Liga regular",
    puntos: 55,
    rebotes: 4,
    valoracion: 4,
  },
  {
    jugador: "Wilt Chamberlain",
    rival: "San Antonio Spurs",
    fase: "Liga regular",
    puntos: 54,
    rebotes: 27,
    valoracion: 37,
  },
  {
    jugador: "Wilt Chamberlain",
    rival: "San Antonio Spurs",
    fase: "Liga regular",
    puntos: 84,
    rebotes: 37,
    valoracion: 17,
  },
  {
    jugador: "Bill Russell",
    rival: "Boston Celtics",
    fase: "Playoff",
    puntos: 85,
    rebotes: 7,
    valoracion: 46,
  },
];
