const listaMovies = [
  {
    codigo: "FAS34",
    titulo: "The Midnight Sun",
    director: "Bong Joon-ho",
    productora: "Cinema Paradiso",
    precio: 7.35,
    idioma: "español",
  },
  {
    codigo: "FMT12",
    titulo: "Echoes of the Past",
    director: "Jordan Peele",
    productora: "Golden Globe Films",
    precio: 5.46,
    idioma: "inglés",
  },
  {
    codigo: "CNO01",
    titulo: "Whispers in the Wind",
    director: "Bong Joon-ho",
    productora: "CineMagic Productions",
    precio: 10.16,
    idioma: "francés",
  },
  {
    codigo: "XHE99",
    titulo: "Shadows of the Moon",
    director: "Alejandro González Iñárritu",
    productora: "Silver Screen Entertainment",
    precio: 7.9,
    idioma: "español",
  },
  {
    codigo: "FHD77",
    titulo: "The Enchanted Forest",
    director: "Christopher Nolan",
    productora: "CineMagic Productions",
    precio: 8.57,
    idioma: "inglés",
  },
  {
    codigo: "UHH98",
    titulo: "Lost in Time",
    director: "Ava DuVernay",
    productora: "Cinema Paradiso",
    precio: 9.45,
    idioma: "alemán",
  },
  {
    codigo: "NDR96",
    titulo: "The Secret Garden",
    director: "Lynne Ramsay",
    productora: "CineMagic Productions",
    precio: 9.85,
    idioma: "español",
  },
  {
    codigo: "FTE03",
    titulo: "Beyond the Horizon",
    director: "Alejandro González Iñárritu",
    productora: "DreamWorks Pictures",
    precio: 14.68,
    idioma: "alemán",
  },
  {
    codigo: "WKR06",
    titulo: "Mystic Waters",
    director: "Ava DuVernay",
    productora: "Blockbuster Films",
    precio: 18.91,
    idioma: "inglés",
  },
  {
    codigo: "QBQ68",
    titulo: "The Forgotten Kingdom",
    director: "Ava DuVernay",
    productora: "Starlight Studios",
    precio: 8.7,
    idioma: "inglés",
  },
  {
    codigo: "XHW81",
    titulo: "The Midnight Sun",
    director: "Bong Joon-ho",
    productora: "Majestic Motion Pictures",
    precio: 16.51,
    idioma: "alemán",
  },
  {
    codigo: "UBA43",
    titulo: "Echoes of the Past",
    director: "Lynne Ramsay",
    productora: "Blockbuster Films",
    precio: 17.42,
    idioma: "francés",
  },
  {
    codigo: "XXB38",
    titulo: "Whispers in the Wind",
    director: "Bong Joon-ho",
    productora: "Cinema Paradiso",
    precio: 6.06,
    idioma: "español",
  },
  {
    codigo: "GGJ35",
    titulo: "Shadows of the Moon",
    director: "Guillermo del Toro",
    productora: "Cinema Paradiso",
    precio: 14.7,
    idioma: "francés",
  },
  {
    codigo: "TQC06",
    titulo: "The Enchanted Forest",
    director: "Greta Gerwig",
    productora: "Moonlight Productions",
    precio: 4.8,
    idioma: "portugués",
  },
  {
    codigo: "FFF83",
    titulo: "Lost in Time",
    director: "Ava DuVernay",
    productora: "Silver Screen Entertainment",
    precio: 9.11,
    idioma: "español",
  },
  {
    codigo: "OQQ89",
    titulo: "The Secret Garden",
    director: "Greta Gerwig",
    productora: "Blockbuster Films",
    precio: 12.11,
    idioma: "inglés",
  },
  {
    codigo: "BDQ73",
    titulo: "Beyond the Horizon",
    director: "Quentin Tarantino",
    productora: "Blockbuster Films",
    precio: 14.95,
    idioma: "francés",
  },
  {
    codigo: "BLX06",
    titulo: "Mystic Waters",
    director: "Greta Gerwig",
    productora: "Blockbuster Films",
    precio: 4.22,
    idioma: "portugués",
  },
  {
    codigo: "ZTN00",
    titulo: "The Forgotten Kingdom",
    director: "Lynne Ramsay",
    productora: "Cinema Paradiso",
    precio: 9.12,
    idioma: "francés",
  },
  {
    codigo: "XPF69",
    titulo: "The Midnight Sun",
    director: "Guillermo del Toro",
    productora: "Starlight Studios",
    precio: 4.05,
    idioma: "alemán",
  },
  {
    codigo: "HTI35",
    titulo: "Echoes of the Past",
    director: "Christopher Nolan",
    productora: "Starlight Studios",
    precio: 17.11,
    idioma: "inglés",
  },
  {
    codigo: "WLX78",
    titulo: "Whispers in the Wind",
    director: "Jordan Peele",
    productora: "CineMagic Productions",
    precio: 5.3,
    idioma: "portugués",
  },
  {
    codigo: "YPC19",
    titulo: "Shadows of the Moon",
    director: "Christopher Nolan",
    productora: "Majestic Motion Pictures",
    precio: 11.02,
    idioma: "alemán",
  },
  {
    codigo: "QKW08",
    titulo: "The Enchanted Forest",
    director: "Quentin Tarantino",
    productora: "Starlight Studios",
    precio: 10.96,
    idioma: "portugués",
  },
  {
    codigo: "PHP73",
    titulo: "Lost in Time",
    director: "Lynne Ramsay",
    productora: "Sunset Studios",
    precio: 14.74,
    idioma: "español",
  },
  {
    codigo: "SWJ78",
    titulo: "The Secret Garden",
    director: "Greta Gerwig",
    productora: "DreamWorks Pictures",
    precio: 6.42,
    idioma: "alemán",
  },
  {
    codigo: "QED56",
    titulo: "Beyond the Horizon",
    director: "Alejandro González Iñárritu",
    productora: "CineMagic Productions",
    precio: 4.95,
    idioma: "español",
  },
  {
    codigo: "DCG95",
    titulo: "Mystic Waters",
    director: "Quentin Tarantino",
    productora: "Majestic Motion Pictures",
    precio: 17.82,
    idioma: "alemán",
  },
  {
    codigo: "PMY48",
    titulo: "The Forgotten Kingdom",
    director: "Ava DuVernay",
    productora: "Sunset Studios",
    precio: 10.22,
    idioma: "portugués",
  },
  {
    codigo: "DDE43",
    titulo: "The Midnight Sun",
    director: "Ava DuVernay",
    productora: "Sunset Studios",
    precio: 8.95,
    idioma: "portugués",
  },
  {
    codigo: "EWE46",
    titulo: "Echoes of the Past",
    director: "Christopher Nolan",
    productora: "DreamWorks Pictures",
    precio: 16.93,
    idioma: "inglés",
  },
  {
    codigo: "SWV43",
    titulo: "Whispers in the Wind",
    director: "Ava DuVernay",
    productora: "Cinema Paradiso",
    precio: 6.76,
    idioma: "alemán",
  },
  {
    codigo: "UOT84",
    titulo: "Shadows of the Moon",
    director: "Sofia Coppola",
    productora: "Blockbuster Films",
    precio: 15.58,
    idioma: "alemán",
  },
  {
    codigo: "JGR07",
    titulo: "The Enchanted Forest",
    director: "Lynne Ramsay",
    productora: "Sunset Studios",
    precio: 4.9,
    idioma: "portugués",
  },
  {
    codigo: "SEQ38",
    titulo: "Lost in Time",
    director: "Sofia Coppola",
    productora: "Blockbuster Films",
    precio: 12.0,
    idioma: "portugués",
  },
  {
    codigo: "JNO97",
    titulo: "The Secret Garden",
    director: "Ava DuVernay",
    productora: "Silver Screen Entertainment",
    precio: 7.55,
    idioma: "portugués",
  },
  {
    codigo: "FLO63",
    titulo: "Beyond the Horizon",
    director: "Bong Joon-ho",
    productora: "Majestic Motion Pictures",
    precio: 12.74,
    idioma: "español",
  },
  {
    codigo: "OED86",
    titulo: "Mystic Waters",
    director: "Quentin Tarantino",
    productora: "Sunset Studios",
    precio: 16.3,
    idioma: "francés",
  },
  {
    codigo: "HOB48",
    titulo: "The Forgotten Kingdom",
    director: "Ava DuVernay",
    productora: "Sunset Studios",
    precio: 17.38,
    idioma: "inglés",
  },
  {
    codigo: "XLS86",
    titulo: "The Midnight Sun",
    director: "Sofia Coppola",
    productora: "Silver Screen Entertainment",
    precio: 11.04,
    idioma: "francés",
  },
  {
    codigo: "IIO80",
    titulo: "Echoes of the Past",
    director: "Jordan Peele",
    productora: "Golden Globe Films",
    precio: 13.73,
    idioma: "portugués",
  },
  {
    codigo: "DZH15",
    titulo: "Whispers in the Wind",
    director: "Guillermo del Toro",
    productora: "Golden Globe Films",
    precio: 4.78,
    idioma: "español",
  },
  {
    codigo: "IXG11",
    titulo: "Shadows of the Moon",
    director: "Sofia Coppola",
    productora: "DreamWorks Pictures",
    precio: 19.74,
    idioma: "inglés",
  },
  {
    codigo: "BSM35",
    titulo: "The Enchanted Forest",
    director: "Ava DuVernay",
    productora: "DreamWorks Pictures",
    precio: 17.21,
    idioma: "alemán",
  },
  {
    codigo: "YXZ51",
    titulo: "Lost in Time",
    director: "Greta Gerwig",
    productora: "Starlight Studios",
    precio: 12.51,
    idioma: "portugués",
  },
  {
    codigo: "RQK25",
    titulo: "The Secret Garden",
    director: "Alejandro González Iñárritu",
    productora: "Silver Screen Entertainment",
    precio: 5.62,
    idioma: "francés",
  },
  {
    codigo: "LKU74",
    titulo: "Beyond the Horizon",
    director: "Lynne Ramsay",
    productora: "Majestic Motion Pictures",
    precio: 13.52,
    idioma: "portugués",
  },
  {
    codigo: "TZJ32",
    titulo: "Mystic Waters",
    director: "Sofia Coppola",
    productora: "Cinema Paradiso",
    precio: 15.68,
    idioma: "inglés",
  },
  {
    codigo: "FUM90",
    titulo: "The Forgotten Kingdom",
    director: "Quentin Tarantino",
    productora: "Majestic Motion Pictures",
    precio: 17.0,
    idioma: "alemán",
  },
];
